package View;

import Beans.Bean_Cadastro;
import Controller.Controller_Alterar;

public class View_Remover extends javax.swing.JInternalFrame {
    
    Bean_Cadastro BC;
    Controller_Alterar CA;
    
    

View_Remover() {
        initComponents();
        
        BC = new Bean_Cadastro();
        CA = new Controller_Alterar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane_Login = new javax.swing.JLayeredPane();
        F_Password = new javax.swing.JPasswordField();
        L_User = new javax.swing.JLabel();
        L_Password = new javax.swing.JLabel();
        F_User = new javax.swing.JTextField();
        B_Login = new javax.swing.JButton();
        L_Password1 = new javax.swing.JLabel();
        F_CPF1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        jLayeredPane_Login.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        jLayeredPane_Login.setToolTipText("Login");

        F_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_PasswordActionPerformed(evt);
            }
        });

        L_User.setText("Usuário:");

        L_Password.setText("Senha:");

        F_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_UserActionPerformed(evt);
            }
        });

        B_Login.setText("REMOVER*");
        B_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LoginActionPerformed(evt);
            }
        });

        L_Password1.setText("CPF:");

        F_CPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_CPF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane_LoginLayout = new javax.swing.GroupLayout(jLayeredPane_Login);
        jLayeredPane_Login.setLayout(jLayeredPane_LoginLayout);
        jLayeredPane_LoginLayout.setHorizontalGroup(
            jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane_LoginLayout.createSequentialGroup()
                        .addGroup(jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(L_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(L_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(L_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F_User)
                            .addComponent(F_Password)
                            .addComponent(F_CPF1)))
                    .addGroup(jLayeredPane_LoginLayout.createSequentialGroup()
                        .addGap(0, 181, Short.MAX_VALUE)
                        .addComponent(B_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jLayeredPane_LoginLayout.setVerticalGroup(
            jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_User)
                    .addComponent(F_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Password)
                    .addComponent(F_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Password1)
                    .addComponent(F_CPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(B_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane_Login.setLayer(F_Password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Login.setLayer(L_User, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Login.setLayer(L_Password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Login.setLayer(F_User, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Login.setLayer(B_Login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Login.setLayer(L_Password1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Login.setLayer(F_CPF1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 65)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REMOVER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_PasswordActionPerformed

    private void F_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_UserActionPerformed

    private void B_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LoginActionPerformed

  FillDados();
  
  if(CA.VerificarLogin(BC)){
      
      
  }
      

    }//GEN-LAST:event_B_LoginActionPerformed

    private void F_CPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_CPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_CPF1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Login;
    private javax.swing.JTextField F_CPF1;
    private javax.swing.JPasswordField F_Password;
    private javax.swing.JTextField F_User;
    private javax.swing.JLabel L_Password;
    private javax.swing.JLabel L_Password1;
    private javax.swing.JLabel L_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane_Login;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    final void FillDados(){

        BC.setCPF1(F_CPF1.getText());
        BC.setUSUARIO(F_User.getText());
        BC.setSENHA(F_Password.getText());
        
    }
}
